// <auto-generated />
namespace EF6.Integration.Console.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class StudentAgeAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentAgeAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202003310305187_StudentAgeAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
